### ISSUE TITLE
Lexeme.lexemeType grammatical > functional

### ISSUE THREAD

**Issue by vadekh** [digitallinguistics/data-format#405]
Discussed in the meeting on 8/10. Distinction should be between `lexical` and `functional` instead of `grammatical`.

**Comment by vadekh** [comment]
NOTE: This is a breaking change

**Comment by dwhieb** [comment]
The issue branch for this should be made off of the v2.0 branch.

**Comment by dwhieb** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[spec] Lexeme.lexemeType: grammatical > functional](https://trello.com/c/voGwBkJ6/91-spec-lexemelexemetype-grammatical-functional)
